### ISSUE TITLE
Last key in combo triggers function regardless.

### ISSUE THREAD

**Issue by schoening** [ccampbell/mousetrap#209]
Following issue. Key combos always trigger on the last key in their sequence.

    Mousetrap.bind('w+e', function() { console.log('w+e') });

Will fire when 'e' is pressed. It should only trigger on the 'w+e' combo..

If I change the combo like so:

    Mousetrap.bind('w+e+1', function() { console.log('w+e+1') });

Now the function triggers when '1' is pressed.

**Comment by ccampbell** [comment]
Keyboard combinations do not work with multiple keys because Mousetrap does not keep track of key state (which keys are down at any moment in time).  That is the only way to achieve something like this, and it is not totally reliable (for example if you were holding a key down before you had your browser window in focus).  

The only allowed modifier keys in Mousetrap are `ctrl`, `alt`, `meta`, and `shift`.  

This is not something that I plan on supporting, but it could be possible to do yourself by attaching listeners for keyup and keydown and keeping track of which keys are down at any one time to manually trigger events.  There are also other keyboard libraries that do allow you to do things like this.
