### ISSUE TITLE
how to click/press button or <a>

### ISSUE THREAD

**Issue by t0n1zz** [ccampbell/mousetrap#241]
Hi, i'm newbie in javascript and i interested to implement shortcut button for my form but how to do click/press into my submit button and my <a> tags?

your documentation only tell how to bind the keyboard keys 

and, is it works the same across browser? because if using accesskey in html feature, the shortcut is different for some browser

**Comment by Nilpo** [comment]
No offense, but it's probably time to read a book first.  Issues are meant for discussing possible issues with the code being offered.  This question is better for a forum or Q&A site like Stack Overflow where you can post the code you have and get help tailored for your situation.

In an attempt to answer your question, forms can already be submitted by pressing the Enter key as long as the submit button has focus.  Otherwise, you need to call your form's submit() method to trigger the submit event when another key event is raised.  Mousetrap can help with that part.

Something like this should do the trick.

    <script src="/path/to/mousetrap.min.js"></script>
    
    <script>
    	var myForm = document.getElementById('myForm');
    
    	// Make the letter 'x' submit the form
    	Mousetrap.bind('x', function() {
    		myForm.submit();
    	});
    </script>

That said, you may want to consider why you want to do this.  This goes against the fundamental behavior that most users will expect when viewing your page.  You want to avoid unexpected behavior  unless you have good reason to do it, or you have a way of making your visitor's aware of the new behavior.  Imagine accidentally tapping the key that submits your form without knowing it would happen.  Sometimes as developers we believe we're simplifying things for our visitors but it really just confuses them.  Anyway, hope this helps.  Good luck!

**Comment by t0n1zz** [comment]
oh sorry and thank you hahahahaha
