### ISSUE TITLE
I can't make alt++ work

### ISSUE THREAD

**Issue by clauslindemann** [ccampbell/mousetrap#243]
The following works like a charm, and binds to the minus key
Mousetrap.bind('alt+-', function () {alert("minus")})

But the binding for the + sign doesn't seem to work
Mousetrap.bind('alt++', function () {alert("plus")})

binding to + without alt works fine

**Comment by Nilpo** [comment]
Which plus key are you using?  The one one the main keyboard or on the number pad?  Have you tried "alt+shift+=" instead?  Without looking, I imagine it has something to do with the plus sign being used as the string delimiter.

**Comment by clauslindemann** [comment]
"alt+shift+=" works fine, I am using the number pad "+" - yeah it looks like "the splitting at +" is the sinner.
Just wondered if you had stumbled upon it before. I will take a look and see if I can make a work around.

BTW awesome mouse killer - thanks!

**Comment by Nilpo** [comment]
I think I have a working case.  Let me test it and put together a pull request.

**Comment by clauslindemann** [comment]
That sounds great!

**Comment by ccampbell** [comment]
@clauslindemann I just pushed a fix to master.  Can you let me know it works for you?

**Comment by clauslindemann** [comment]
Hi Craig – here is a little report


Alt++ working with numeric keypad
Alt++ doesn't work when using main keyboard

Alt+- works with numeric keypad
Alt+- works with main keyboard

I wondered if the Alt++ problem was due to me running
a danish keyboard

danish layout -> http://fontmeme.com/images/danish-keyboard-550x183.png

so I tried switching to us-english layout, but that doesn't seem to help
( I am pressing Alt+Shift+<one key to the left from backspace> on the
us-english layout

us-english layout ->
http://en.wikipedia.org/wiki/File:KB_US-International.svg

Btw thanks a lot for working on this

Cheers
Claus

ᐧ

2015-03-28 3:35 GMT+01:00 Craig Campbell <notifications@github.com>:

**Comment by ccampbell** [comment]
I'm aware about the limitation, but I'm not sure there is much I can do about it.  I'm don't know about international keyboards, but in the US the `+` key is really `shift+=`.  When you hold the `alt` key and press the plus key, the keypress event returns the key for `≠` which for some reason I can't get mousetrap to listen for (possibly another bug).  

I fixed it for the numeric keypad cause that plus sign does not require holding shift.  For US keyboards if you bind to `alt+=` or `alt+shift+=` (depending on which you want) in addition to `alt++` then it should work as expected, but that will not necessarily carry over to other keyboard layouts.

The complete sequence of events for holding `alt+shift+=` is

```
keydown alt
keydown shift
keydown =
keypress ±
keyup =
keyup shift
keyup alt
```

In general binding to keys that require holding shift while also expecting the alt key to be pressed is somewhat problematic since the alt key actually alters the key that you are pressing.  I'm open to ideas though.

**Comment by clauslindemann** [comment]
I think that binding to the plus key is probably more convenient on
keyboard layouts
where you are not required to hold down the shift key first. I missed this
point since
a lot of european keyboards has "plus" mapped to a single keypress. So
anyway
my app will probably benefit from a more general keymapping ( I used Alt ++
to
add a new file )

For accessibility it is probably for the better that I stick to mappings
that requires
simpler combinations, I do appreciate that it works on the numeric keyboard
though

I don't have any better ideas than those you layout currently, but I will
take a look
and see if anything pops up.

Again - thanks a lot Craig

cheers Claus
ᐧ

2015-03-28 14:45 GMT+01:00 Craig Campbell <notifications@github.com>:
