### ISSUE TITLE
Unit test 'return false should prevent default and stop propagation' broken

### ISSUE THREAD

**Issue by mightyiam** [ccampbell/mousetrap#252]
It is [fixed in my spork](https://github.com/PolicyStat/combokeys/pull/37/files#r27298540).

**Comment by mightyiam** [comment]
https://github.com/ccampbell/mousetrap/blob/748d7ece33a3792ceb815540896f4aedc692a10d/tests/test.mousetrap.js#L147

**Comment by ccampbell** [comment]
Thanks.  There were two issues, I wasn't catching the error cause I was calling `.to.be.True` instead of `.to.be.true`.

The other issue is that cancelBubble is not correctly set to true when you call event.stopPropagation().  It should be though:

https://code.google.com/p/chromium/issues/detail?id=162270

**Comment by mightyiam** [comment]
There are two things to check here. One is that default is prevented and the other is the propagation is stopped.

The [way I settled for](https://github.com/PolicyStat/combokeys/blob/85c0c86e8b6c88a2119d01d1f91c8fb91a012c29/test/test.combokeys.js#L178-L229) tests both across IE8+ and modern browsers.
