### ISSUE TITLE
Any support for `fn` key on Mac?

### ISSUE THREAD

**Issue by norbertpy** [ccampbell/mousetrap#343]
Do you guys have any support for `fn` key on Mac? I don't seem to find related info.

**Comment by angularcircle** [comment]
Maybe consider checking out section number VII of the _mousetrap API reference_. There is an option `addKeycodes`, that allows you to support custom keys (you just need to check what key code is used on your machine when you're pressing the `Fn` key): 
https://craig.is/killing/mice#api.addKeycodes
```js
Mousetrap.addKeycodes({
    144: 'numlock'
});
```

KeyCode of this button you can get by writng simple handler in JS or check on some site like (at the bottom of the page there is _testing textarea_): http://www.quirksmode.org/js/keys.html

I do not own Mac, so I can't test it but on my machine `Fn` keys are ignored by the browser (tested in current FF/linux) so there is no way that _MouseTrap_ (or any JS based solution for webbrowser since no events are emited when they are used) will be able handle it (at least for now).

**Comment by norbertpy** [comment]
@angularcircle Thank you.
