### ISSUE TITLE
`-` keystroke not registering

### ISSUE THREAD

**Issue by aaron-m-kent** [ccampbell/mousetrap#389]
Should the minus key `-` work as a normal reference? Is there a `minus` or `substract`? Nothing seems to work for that key. Thanks.

**Comment by hackape** [comment]
It should work. However, if you are on macOS and you bind to `'ctrl+-'` then you'll fail because the OS has this shortcut bound to "Move focus to the menu bar", thus the keyboard event never reached the browser. It's kinda hard to notice.

![image](https://user-images.githubusercontent.com/8945315/29351315-d136d1d0-8294-11e7-8a03-12c8be5eb4dc.png)

**Comment by aaron-m-kent** [comment]
Thanks for the clarification! It was indeed a macOS issue.

**Comment by eyerean** [comment]
I have no shortcuts on my mac registered with '-', and yet the '-' keystroke was not recognized.

I fixed it adding this line `Mousetrap.addKeycodes({173: '-'});` as described [before](https://github.com/ccampbell/mousetrap/pull/215#issuecomment-288808671).
